_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: '/home/user/models/M2/step_gru_best_model.pt'
  OUTPUT_DIM: 8
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_M2.pt'  

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/M2_Alabama+BBN_videos.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/M2_Alabama+BBN_videos.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/M2_Alabama+BBN_videos.csv"

OUTPUT:
  LOCATION: "/home/user/output"

SKILLS:
  - NAME: M2 - Apply Tourniquet
    STEPS:
    - Place tourniquet over affected extremity 2-3 inches above wound site.
    - Pull tourniquet tight.
    - Apply strap to strap body.
    - Turn windless clock wise or counter clockwise until hemorrhage is controlled.
    - Lock windless into the windless keeper.
    - Pull remaining strap over the windless keeper.
    - Secure strap and windless keeper with keeper securing device.
    - Mark time on securing device strap with permanent marker.    
