_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: '/home/user/models/M3/step_gru_best_model.pt'
  OUTPUT_DIM: 5
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_M3.pt'  

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/M3_Alabama+BBN_videos.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/M3_Alabama+BBN_videos.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/M3_Alabama+BBN_videos.csv"

OUTPUT:
  LOCATION: "/home/user/output"  
  
SKILLS:
  - NAME: M3 - Apply pressure dressing
    STEPS:
    - Apply direct hand pressure.
    - Open dressing packaging.
    - Apply dressing with pressure point directly over wound site.
    - Wrap dressing around affected area extremity or trunk with 80 percent elastic stretch.
    - Secure dressing with securing device.
