_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: '/home/user/models/M5/step_gru_best_model.pt'
  OUTPUT_DIM: 5
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_M5.pt'  

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/M5_Alabama+BBN_videos.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/M5_Alabama+BBN_videos.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/M5_Alabama+BBN_videos.csv"

OUTPUT:
  LOCATION: "/home/user/output"  

SKILLS:
  - NAME: M5 - X-Stat
    STEPS:
    - Open inner packaging and remove applicator.
    - Insert applicator into wound track as close to bleeding source as possible.
    - Insert plunger into applicator.
    - Push plunger firmly to deploy sponges into wound.
    - Apply manual pressure if necessary.    
