_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: '/home/user/models/R18/step_gru_best_model.pt'
  OUTPUT_DIM: 5
  YOLO_CHECKPOINT_URL: '/home/user/models/bbn_yolo_R18.pt'  

DATASET:
  TR_ANNOTATIONS_FILE: "/home/user/labels/R18_Alabama+BBN_videos.csv"
  VL_ANNOTATIONS_FILE: "/home/user/labels/R18_Alabama+BBN_videos.csv"
  TS_ANNOTATIONS_FILE: "/home/user/labels/R18_Alabama+BBN_videos.csv"

OUTPUT:
  LOCATION: "/home/user/output"    

SKILLS:
  - NAME: R18 - Apply chest seal
    STEPS:
    - With gloved hand, cover and seal wound site. 
    - Open vented chest seal package.
    - Wipe blood and body fluids from wound site.
    - Peel away chest seal backer.
    - Place chest seal with circle of vents over wound site and seal to chest.
