MODEL:
  HIDDEN_SIZE: 1024
  CONTEXT_LENGTH: 'full'
##Milly  
#  OUTPUT_DIM: 42
#  SKILLS: ['pinwheels', 'coffee', 'mugcake']
#  DRIVE_ID: 1ArZFX4LuuB4SbmmWSDit4S8gPhkc2DRq
##BBN-M1-Trauma-Assessment
#  OUTPUT_DIM: 13
#  SKILLS: ['trauma']
#  DRIVE_ID: ""
##BBN-M2-Tourniquet
#  OUTPUT_DIM: 8
#  SKILLS: ['tourniquet']
#  DRIVE_ID: 1ArZFX4LuuB4SbmmWSDit4S8gPhkc2DRq
#  DRIVE_ID: ""
##BBN-M3-Pressure-Dressing
  OUTPUT_DIM: 5
  SKILLS: ['pressure']
  DRIVE_ID: ""
##BBN-M5-X-Stat
#  OUTPUT_DIM: 6 # offset 34
#  SKILLS: ['m5']
#  DRIVE_ID: 1SWl9ZZtX1xO6oSNFx5NueEbSP5K6IifE
##    
  USE_ACTION: True   ##default true
  USE_OBJECTS: True   ##default true
  USE_AUDIO: False    ##default false
  USE_BN: False      ##default false
  #  CHECKPOINT_FILE_PATH: "/home/user/procedural_step_recog/models/STEPGRU_tourniquet.pt"
  #  CHECKPOINT_FILE_PATH: "/home/user/data/BBN/new/M1/feature/omnimix/step_gru_best_model.pt"
  APPEND_OUT_POSITIONS: 3
DATASET:
  NAME: 'Milly'
  LOCATION: '/omnivore'
  AUDIO_LOCATION: ''
  OBJECT_FRAME_LOCATION: '/obj_frame'
  VIDEO_LAYER: 'shoulders'
  TR_ANNOTATIONS_FILE: "/homse/user/data/BBN/new/M1/labels/BBN-M1_train_90p.csv"
  VL_ANNOTATIONS_FILE: "/homse/user/data/BBN/new/M1/labels/BBN-M1_test_10p.csv"
  TS_ANNOTATIONS_FILE: "/homse/user/data/BBN/new/M1/labels/BBN-M1_test_10p.csv"
  INCLUDE_IMAGE_AUGMENTATIONS: True
  INCLUDE_TIME_AUGMENTATIONS: False
  FPS: 30
  HOP_SIZE: 0.5 # in seconds
  WIN_LENGTH: 2  #in seconds
DATALOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TRAIN:
  ENABLE: True
  NUM_GPUS: 1
  BATCH_SIZE: 32
  OPT: "rmsprop"  #adam sgd rmsprop
  LR: 0.001
  EPOCHS: 15
OUTPUT:
  LOCATION: '/homse/user/data/BBN/new/M1/feature/omnimix'  
