MODEL:
  HIDDEN_SIZE: 1024
  CONTEXT_LENGTH: 'full'
  USE_ACTION: True  ##default true
  USE_OBJECTS: True  ##default true
  USE_AUDIO: False  ##default false
  USE_BN: False      ##default false
  DROP_OUT: 0.5

  OMNIVORE_CONFIG: '/home/user/data/config/OMNIVORE.yaml'
  SLOWFAST_CONFIG: '/home/user/data/auditory_slowfast/configs/BBN/SLOWFAST_R50.yaml'
DATASET:
  NAME: 'Milly'
  CLASS: 'Milly_multifeature_v4'
  LOCATION: '/frame' 
  AUDIO_LOCATION: '/sound'
  INCLUDE_IMAGE_AUGMENTATIONS: True
  INCLUDE_TIME_AUGMENTATIONS: False
  IMAGE_AUGMENTATION_PERCENTAGE: 0.8
DATALOADER:
  NUM_WORKERS: 12
  PIN_MEMORY: True
TRAIN:
  ENABLE: True
  USE_CROSS_VALIDATION: True ##default true
  USE_CLASS_WEIGHT: True ##default true
  NUM_GPUS: 1
  BATCH_SIZE: 8 #32
  OPT: "adam"  #adam sgd rmsprop
  LR: 0.001
  EPOCHS: 25
  CV_TEST_TYPE: None  # 10p bbn None
